### ISSUE TITLE
Is this project DEAD? (canary issue)

### ISSUE THREAD

**Issue by ms-ati** [thomvaill/log4brains#113]
Hi @thomvaill, thank you so much for your work on log4brains.

Noting no responses and no commits for over a year, I am here to sadly ask if this project is now dead, abandoned, no longer actively maintained?

Please respond if you consider this a living and maintained project.

---
🐦 Canary issue - if never responded to, this project can be considered abandoned

**Comment by evanerwee** [comment]
I have attempted to contact the author on several contact points, but the last recorded activity on social media was 8 months ago. I would like to fork the code and continue the development. I'm not sure what the implications would be.

**Comment by fire** [comment]
I switched to https://quarto.org/ to record my decisions https://github.com/V-Sekai/manuals.

**Comment by evanerwee01** [comment]
Thank you for the reply

**Comment by Potherca** [comment]
@evanerwee Could you please jump in at https://github.com/thomvaill/log4brains/discussions/108 ?

There is talk of a community fork there.

**Comment by PauwelsPieter** [comment]
Maintainer reaction (2023/11/18): https://github.com/thomvaill/log4brains/discussions/108#discussioncomment-7607483

**Comment by thomvaill** [comment]
Hi everyone! Sorry for this long silence.
Indeed I paused the project for personal reasons but it is not dead, I am back on track and I took some actions to encourage contributions and share my maintainer responsibilities.
I close this issue and we can continue to chat about this in Discussion #108
