### ISSUE TITLE
log4brains is not maintained

### ISSUE THREAD

**Issue by fire** [thomvaill/log4brains#29]
# Bug Report

## Description

https://github.com/thomvaill/log4brains/issues/27 has been open for 1 month and has not been resolved.

## Steps to Reproduce

Run cicd Github Actions and watch the build break.

## Expected Behavior

Resolved breakage within a month.

## Context

* Unable to use log4brains
* Evaluating use for documentation

**Comment by thomvaill** [comment]
Hi @fire 

I totally understand your concern, and I apologize for my long absence...
#27 is now fixed, and as [I explained there](https://github.com/thomvaill/log4brains/issues/27#issuecomment-829959345):

> Leaving a bug like this one not resolved for 2 months is just a shame!! 😱
> I had a lot of work in March and got the Covid at the beginning of April (hopefully not severe!) but from now on I will be able to work on the project again in my spare time! 🙏

So, no worries, the project is still maintained :-)

By the way, contributors are very welcome! I now work on the project only in my spare time, so if you or someone else want to work with me on it, it would be a real pleasure!
