### ISSUE TITLE
Project Branding

### ISSUE THREAD

**Issue by fire** [thomvaill/log4brains#40]
# Bug Report

## Description

Log4Brain does not SEO the project. Instead it SEOs log4brains.

## Steps to Reproduce

Use the Log4Brains to export a website. Look at the title.

## Expected Behavior

It should use the project name and not `log4brains`.

## Context

Want to brand the repository.

## Environment

- Log4brains version: 6c82030
- Node.js version: ?
- OS and its version: win10
- Browser information: firefox

**Comment by e0ipso** [comment]
I am also interested in this feature. @thomvaill is this something you are looking for contributions, or in your roadmap?

**Comment by fire** [comment]
Closing due to a switch to a different software.

**Comment by deviantintegral** [comment]
We ended up writing a generator with Gatsby, which supports themes: https://github.com/Lullabot/gatsby-theme-adr
