### ISSUE TITLE
cannot read property 'incrementalOptions' of undefined

### ISSUE THREAD

**Issue by Dutzu** [thomvaill/log4brains#78]
# Bug Report

## Description

Regression of a previous bug report from last year regarding a NextJS Hack. [issue #27](https://github.com/thomvaill/log4brains/issues/27)

## Steps to Reproduce

1. Installed the latest version of the log4brains.
2. `log4brains init`
3. `log4brains preview` fails with the error:
`FATAL  Cannot read property 'incrementalOptions' of undefined`
4. `log4brains build` works and the output is generated but not entirely.

## Environment

Log4brains version: 1.0.0-beta.8
Node.js version: v14.19.0 & v16.15.0
OS and its version: MacOS v12.3.1
Browser information: NA

## Possible Solution 

Fixed reference to NextJS

**Comment by manutepowa** [comment]
I have the same problem.


Log4brains version: 1.0.0-beta.12
Node.js version: v14.19.3
Npm: 6.14.17
OS and its version: Ubuntu 20.04

**Comment by fabianem** [comment]
Same problem here.

Log4brains version: 1.0.0-beta.12
Node.js version: v18.0.0
Npm: 8.6.0
OS: MacOS v12.4 (M1)

**Comment by Sobi-WanKenobi** [comment]
Same problem here.

Log4brains version: 1.0.0-beta.12
Node.js version: v17.8.0
Npm: 8.5.5
OS and its version: 
  System Version:	macOS 12.3.1 (21E258)
  Kernel Version:	Darwin 21.4.0

**Comment by indatawetrust** [comment]
fixed in https://github.com/thomvaill/log4brains/pull/79

**Comment by thomvaill** [comment]
Thank you @Dutzu for the report and thank you @indatawetrust for the fix in #79 !
Released in beta-13
